const languageData = {
  ko: {
    terminal: "제1여객터미널",
    update: "업데이트",
    departureHallCongestion: "출국장 혼잡도",
    departurehall: "출국장",
    showMap: "약도 보기",
    west: "서편",
    east: "동편",
    congestion: "혼잡도",
    none: "미사용",
    low: "여유",
    medium: "보통",
    high: "혼잡",
    veryhigh: "매우혼잡",
    distance: "거리",
    boardingGate: "탑승구",
    gate1: "1출국장",
    gate2: "2출국장",
    gate3: "3출국장",
    gate4: "4출국장",
    gate5: "5출국장",
    gate6: "6출국장",
    korean: "한국어",
    ko: "한국어",
    chinese: "중국어",
    zh: "중국어",
    japenese: "일본어",
    ja: "일본어",
    english: "영어",
    en: "영어",
    current: "사용중",
    am: "오전",
    pm: "오후",
    immigration: "출국심사",
    nthGate: "{{number}}번 탑승구",
    first: "1순위",
    second: "2순위",
    third: "3순위",
    hour: "시간",
    minute: "분",
    estimated: "예상 소요 시간",
    estimatedTime: "구간별 예상 소요시간",
    totalTime: "총 {{hour}}시간 {{minute}}분",
    selectHall: "출국장 선택",
    waitingTime: "심사 대기 시간",
    total: "총",
    transfer: "이동",
    walk: "도보",
    Immigration: "심사",
    needTrain: "셔틀 트레인 탑승이 필요한 탑승구입니다.",
    checkNum: "잘못된 게이트 번호입니다. 다시 확인해 주세요.",
    gateNum: "탑승구 번호를 입력해주세요.",
    tryMeal: "출국 전 든든한 한 끼 어떠신가요?",
    modalTitle: "인천공항 맛집 BEST 10!",
    modalBtn: "인천공항 맛집 보러가기",
  },
  ja: {
    terminal: "第1旅客ターミナル",
    update: "更新",
    departureHallCongestion: "出発ホールの混雑状況",
    departurehall: "出発ホール",
    showMap: "地図を見る",
    west: "西側",
    east: "東側",
    congestion: "混雑状況",
    none: "未使用",
    low: "円滑",
    medium: "普通",
    high: "混雑",
    veryhigh: "非常に混雑",
    distance: "距離",
    boardingGate: "搭乗ゲート",
    gate1: "1番出発ホール",
    gate2: "2番出発ホール",
    gate3: "3番出発ホール",
    gate4: "4番出発ホール",
    gate5: "5番出発ホール",
    gate6: "6番出発ホール",
    korean: "韓国語",
    ko: "韓国語",
    chinese: "中国語",
    zh: "中国語",
    japenese: "日本語",
    ja: "日本語",
    english: "英語",
    en: "英語",
    current: "使用中",
    am: "午前",
    pm: "午後",
    immigration: "出国審査",
    nthGate: "搭乗口{{number}}番",
    first: "第1番",
    second: "第2番",
    third: "第3番",
    hour: "時間",
    minute: "分",
    estimated: "所要時間",
    estimatedTime: "区間別の所要時間（予想）",
    totalTime: "合計 {{hour}}時間 {{minute}}分",
    selectHall: "出発ゲートを選択",
    waitingTime: "審査待ち時間",
    total: "合計",
    transfer: "乗り継ぎ",
    walk: "徒歩",
    Immigration: "審査",
    needTrain: "この搭乗口へはシャトルトレインの乗車が必要です。",
    checkNum: "無効な搭乗口番号です。もう一度ご確認ください。",
    gateNum: "搭乗口番号を入力してください。",
    tryMeal: "ご出発前に、しっかりとお食事いかがですか?",
    modalTitle: "仁川空港のグルメおすすめ10選",
    modalBtn: "仁川空港のグルメを見る",
  },
  zh: {
    update: "更新时间",
    departureHallCongestion: "出发大厅拥堵情况",
    departurehall: "出发大厅",
    showMap: "查看地图",
    west: "西侧",
    east: "东侧",
    congestion: "拥挤状况",
    none: "未使用",
    low: "顺畅",
    medium: "一般",
    high: "拥堵",
    veryhigh: "非常拥堵",
    distance: "距离",
    boardingGate: "登机口",
    gate1: "1号出发大厅",
    gate2: "2号出发大厅",
    gate3: "3号出发大厅",
    gate4: "4号出发大厅",
    gate5: "5号出发大厅",
    gate6: "6号出发大厅",
    korean: "韩语",
    ko: "韩语",
    chinese: "中文",
    zh: "中文",
    japenese: "日语",
    ja: "日语",
    english: "英语",
    en: "英语",
    current: "使用中",
    am: "上午",
    pm: "下午",
    immigration: "出境检查",
    nthGate: "{{number}}号登机口",
    first: "第1个",
    second: "第二个",
    third: "第三个",
    hour: "小时",
    minute: "分钟",
    estimated: "耗时",
    estimatedTime: "各区间预计耗时",
    totalTime: "总计 {{hour}}小时 {{minute}}分",
    selectHall: "请选择出境大厅",
    waitingTime: "出境检查等候时间",
    total: "总计",
    transfer: "中转",
    walk: "步行",
    Immigration: "审查",
    needTrain: "前往此登机口需搭乘摆渡列车。",
    checkNum: "登机口号码无效。请重新确认。",
    gateNum: "请输入登机口号码。",
    tryMeal: "出国前，来一顿丰盛的餐吧!",
    modalTitle: "仁川机场美食TOP 10!",
    modalBtn: "	查看仁川机场美食",
  },
  en: {
    terminal: "Passenger Terminal 1",
    update: "UPDATE",
    departureHallCongestion: "Departure Hall Congestion",
    departurehall: "Departure \n Hall",
    showMap: "View Map",
    west: "West",
    east: "East",
    congestion: "Crowd Level",
    none: "Not in use",
    low: "Smooth",
    medium: "Normal",
    high: "Crowded",
    veryhigh: "Very Crowded",
    distance: "distance",
    boardingGate: "Boarding Gate",
    gate1: "Departure <br>Hall 1",
    gate2: "Departure <br>Hall 2",
    gate3: "Departure <br>Hall 3",
    gate4: "Departure <br>Hall 4",
    gate5: "Departure <br>Hall 5",
    gate6: "Departure <br>Hall 6",
    korean: "KOR",
    ko: "Korean",
    chinese: "CHN",
    zh: "Chinese",
    japenese: "JP",
    ja: "Japanese",
    english: "ENG",
    en: "English",
    current: "In Use",
    am: "am",
    pm: "pm",
    immigration: "Immigration",
    nthGate: "Boarding Gate {{number}}",
    first: "1st",
    second: "2nd",
    third: "3rd",
    hour: "h",
    minute: "min",
    estimated: "Estimated Time",
    estimatedTime: "Estimated Time by Section",
    totalTime: "Total {{hour}}h {{minute}}m",
    selectHall: "Select Departure Hall",
    waitingTime: "Waiting Time",
    total: "total",
    transfer: "transfer",
    walk: "walk",
    Immigration: "Immigration",
    needTrain: "A shuttle train is required to reach this gate.",
    checkNum: "The gate number is invalid. Please check again.",
    gateNum: "Please enter your gate number.",
    tryMeal: "How about a hearty meal before your flight?",
    modalTitle: "Top 10 Must-Try Eats at Incheon Airport!",
    modalBtn: "View Incheon Airport Eats",
  },
};
