const languageData = {
  ko: {
    terminal: "제1여객터미널",
    update: "업데이트",
    departureHallCongestion: "출국장 혼잡도",
    departurehall: "출국장",
    showMap: "약도 보기",
    west: "서편",
    east: "동편",
    congestion: "혼잡도",
    none: "미사용",
    low: "여유",
    medium: "보통",
    high: "혼잡",
    veryhigh: "매우혼잡",
    distance: "거리",
    boardingGate: "탑승게이트",
    gate1: "1출국장",
    gate2: "2출국장",
    gate3: "3출국장",
    gate4: "4출국장",
    gate5: "5출국장",
    gate6: "6출국장",
    korean: "한국어",
    ko: "한국어",
    chinese: "중국어",
    zh: "중국어",
    japenese: "일본어",
    ja: "일본어",
    english: "영어",
    en: "영어",
    current: "사용중",
    am: "오전",
    pm: "오후",
    immigration: "출국심사",
    nthGate: "{{number}}번 탑승구",
  },
  ja: {
    terminal: "第1旅客ターミナル",
    update: "更新",
    departureHallCongestion: "出発ホールの混雑状況",
    departurehall: "出発ホール",
    showMap: "地図を見る",
    west: "西側",
    east: "東側",
    congestion: "混雑状況",
    none: "未使用",
    low: "円滑",
    medium: "普通",
    high: "混雑",
    veryhigh: "非常に混雑",
    distance: "距離",
    boardingGate: "搭乗ゲート",
    gate1: "1番出発ホール",
    gate2: "2番出発ホール",
    gate3: "3番出発ホール",
    gate4: "4番出発ホール",
    gate5: "5番出発ホール",
    gate6: "6番出発ホール",
    korean: "韓国語",
    ko: "韓国語",
    chinese: "中国語",
    zh: "中国語",
    japenese: "日本語",
    ja: "日本語",
    english: "英語",
    en: "英語",
    current: "使用中",
    am: "午前",
    pm: "午後",
    immigration: "出国審査",
    nthGate: "搭乗口{{number}}番",
  },
  zh: {
    update: "更新时间",
    departureHallCongestion: "出发大厅拥堵情况",
    departurehall: "出发大厅",
    showMap: "查看地图",
    west: "西侧",
    east: "东侧",
    congestion: "拥挤状况",
    none: "未使用",
    low: "顺畅",
    medium: "一般",
    high: "拥堵",
    veryhigh: "非常拥堵",
    distance: "距离",
    boardingGate: "登机口",
    gate1: "1号出发大厅",
    gate2: "2号出发大厅",
    gate3: "3号出发大厅",
    gate4: "4号出发大厅",
    gate5: "5号出发大厅",
    gate6: "6号出发大厅",
    korean: "韩语",
    ko: "韩语",
    chinese: "中文",
    zh: "中文",
    japenese: "日语",
    ja: "日语",
    english: "英语",
    en: "英语",
    current: "使用中",
    am: "上午",
    pm: "下午",
    immigration: "出境检查",
    nthGate: "{{number}}号登机口",
  },
  en: {
    terminal: "Passenger Terminal 1",
    update: "UPDATE",
    departureHallCongestion: "Departure Hall Congestion",
    departurehall: "Departure \n Hall",
    showMap: "View Map",
    west: "West",
    east: "East",
    congestion: "Crowd Level",
    none: "Not in use",
    low: "Smooth",
    medium: "Normal",
    high: "Crowded",
    veryhigh: "Very Crowded",
    distance: "distance",
    boardingGate: "Boarding Gate",
    gate1: "Departure \nHall 1",
    gate2: "Departure \nHall 2",
    gate3: "Departure \nHall 3",
    gate4: "Departure \nHall 4",
    gate5: "Departure \nHall 5",
    gate6: "Departure \nHall 6",
    korean: "KOR",
    ko: "Korean",
    chinese: "CHN",
    zh: "Chinese",
    japenese: "JP",
    ja: "Japanese",
    english: "ENG",
    en: "English",
    current: "In Use",
    am: "am",
    pm: "pm",
    immigration: "immigration",
    nthGate: "Gate {{number}}",
  },
};
