const languageData = {
  ko: {
    terminal: "제1여객터미널",
    update: "업데이트",
    departureHallCongestion: "출국장 혼잡도",
    departurehall: "출국장",
    showMap: "약도 보기",
    west: "서편",
    east: "동편",
    congestion: "혼잡도",
    none: "미사용",
    low: "여유",
    medium: "보통",
    high: "혼잡",
    veryhigh: "매우혼잡",
    distance: "거리",
    // 모든 게이트 추가
    gate1: "1출국장",
    gate2: "2출국장",
    gate3: "3출국장",
    gate4: "4출국장",
    gate5: "5출국장",
    gate6: "6출국장",
  },
  ja: {
    terminal: "第1旅客ターミナル",
    update: "更新",
    departureHallCongestion: "出発ホールの混雑状況",
    departurehall: "出発ホール",
    showMap: "地図を見る",
    west: "西側",
    east: "東側",
    congestion: "混雑状況",
    none: "未使用",
    low: "円滑",
    medium: "普通",
    high: "混雑",
    veryhigh: "非常に混雑",
    distance: "距離",
    // 모든 게이트 추가
    gate1: "1番出発ホール",
    gate2: "2番出발ホール",
    gate3: "3番出발ホール",
    gate4: "4番出発ホール",
    gate5: "5番出発ホール",
    gate6: "6番出発ホール",
  },
  zh: {
    update: "更新时间",
    departureHallCongestion: "出发大厅拥堵情况",
    departurehall: "出发大厅",
    showMap: "查看地图",
    west: "西侧",
    east: "东侧",
    congestion: "拥挤状况",
    none: "未使用",
    low: "顺畅",
    medium: "一般",
    high: "拥堵",
    veryhigh: "非常拥堵",
    distance: "距离",
    // 모든 게이트 추가
    gate1: "1号出发大厅",
    gate2: "2号出发大厅",
    gate3: "3号出发大厅",
    gate4: "4号出发大厅",
    gate5: "5号出发大厅",
    gate6: "6号出发大厅",
  },
  en: {
    terminal: "Passenger Terminal 1",
    update: "UPDATE",
    departureHallCongestion: "Departure Hall Congestion",
    departurehall: "Departure Hall",
    showMap: "View Map",
    west: "West",
    east: "East",
    congestion: "Crowd Level",
    none: "Not in use",
    low: "Smooth",
    medium: "Normal",
    high: "Crowded",
    veryhigh: "Very Crowded",
    distance: "distance",
    // 모든 게이트 추가
    gate1: "Departure Hall 1",
    gate2: "Departure Hall 2",
    gate3: "Departure Hall 3",
    gate4: "Departure Hall 4",
    gate5: "Departure Hall 5",
    gate6: "Departure Hall 6",
  },
};
